version: '3'
services:
  master:
    image: hadoop_spark
    container_name: master
    hostname: master
    command: >
      bash -c "
        sudo service ssh restart &&
        start-all.sh &&
        /home/hduser/spark/sbin/start-all.sh &&
        jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' 2>/dev/null &
        bash
      "
    tty: true
    stdin_open: true
    depends_on:
      - db
      - mongodb
    networks:
      - cluster
    ports:
      - 7077:7077
      - 8080:8080
      - 8088:8088
      - 8888:8888
      - 9870:9870
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - cluster
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    networks:
      - cluster
networks:
  cluster:
    name: hadoop-spark-net
    driver: bridge
volumes:
  db:
    driver: local
  mongodb:
    driver: local
